#!/bin/sh
set -euo pipefail
shopt -s failglob

THIS_FILE=$(readlink -f "$0")
BASEDIR=$(dirname "$THIS_FILE")

function rm_folder_if_exists() {
  if test -d $BASEDIR/$1
  then
    rm -r $BASEDIR/$1
  fi
}
function rm_file_if_exists() {
  if test -f $BASEDIR/$1
  then
    rm $BASEDIR/$1
  fi
}

rm_folder_if_exists release
rm_folder_if_exists .gradle
rm_folder_if_exists build
rm_folder_if_exists lib/.cxx
rm_folder_if_exists lib/build
rm_folder_if_exists tests/.cxx
rm_folder_if_exists tests/build
rm_folder_if_exists sampleapp/.gradle
rm_folder_if_exists sampleapp/build
rm_folder_if_exists sampleapp/app/.cxx
rm_folder_if_exists sampleapp/app/build
rm_file_if_exists sampleapp/app/libs/tmpfile-android-1.0.0.aar

exit 0
rm_folder_if_exists .idea
rm_file_if_exists tests/tests.iml
rm_file_if_exists tmpfile-android.iml
rm_file_if_exists lib/lib.iml

rm_folder_if_exists sampleapp/.idea
rm_file_if_exists sampleapp/sampleapp.iml
rm_file_if_exists sampleapp/app/app.iml
