#!/bin/sh
set -euo pipefail
shopt -s failglob

THIS_FILE=$(readlink -f "$0")
BASEDIR=$(dirname "$THIS_FILE")

function rm_folder_if_exists() {
  if test -d $BASEDIR/$1
  then
    rm -r $BASEDIR/$1
  fi
}

rm_folder_if_exists build
rm_folder_if_exists android/.gradle
rm_folder_if_exists android/build
rm_folder_if_exists android/tmpfile/.cxx
rm_folder_if_exists android/tmpfile/build
rm_folder_if_exists android/tests/.cxx
rm_folder_if_exists android/tests/build
rm_folder_if_exists sampleapp/.gradle
rm_folder_if_exists sampleapp/build
rm_folder_if_exists sampleapp/app/.cxx
rm_folder_if_exists sampleapp/app/build
rm_folder_if_exists sampleapp/app/libs/tmpfile.aar

