#!/bin/sh
set -eu

THIS_FILE=$(readlink -f "$0")
BASEDIR=$(dirname "$THIS_FILE")

function rm_folder_if_exists() {
  if test -d $BASEDIR/$1
  then
    rm -r $BASEDIR/$1
  fi
}
function rm_file_if_exists() {
  if test -f $BASEDIR/$1
  then
    rm $BASEDIR/$1
  fi
}

rm_folder_if_exists .gradle
rm_folder_if_exists build
rm_folder_if_exists tmpfile/.cxx
rm_folder_if_exists tmpfile/build
rm_folder_if_exists sampleapp/.gradle
rm_folder_if_exists sampleapp/build
rm_folder_if_exists sampleapp/app/.cxx
rm_folder_if_exists sampleapp/app/build

rm_folder_if_exists .idea
rm_file_if_exists tmpfile-android.iml
rm_file_if_exists tmpfile/tmpfile.iml

rm_folder_if_exists sampleapp/.idea
rm_file_if_exists sampleapp/sampleapp.iml
rm_file_if_exists sampleapp/app/app.iml
