#!/bin/sh
PROJECT='tmpfile'

set -euo pipefail
shopt -s failglob

THIS_FILE=$(readlink -f "$0")
BASEDIR=$(dirname "$THIS_FILE")
ANDROID_DIR=$BASEDIR/android
RELEASE_DIR=$BASEDIR/release

$BASEDIR/doclean
mkdir --parents $RELEASE_DIR

# Extract project version from build.gradle
# Format:
# android { .... defaultConfig { ... versionName "0.9" ... } ... }
GRADLE_FILE=$ANDROID_DIR/tmpfile/build.gradle
version_format='([0-9\.]+)'
expression="s/.*?versionName \"$version_format\".*?/\1/p"
VERSION=$(tr "\n" ' ' < $GRADLE_FILE | sed -En "--expression=$expression")
echo "Packaging $PROJECT-$VERSION"

TAR_SOURCE=$RELEASE_DIR/$PROJECT-$VERSION-source.tar
tar --create --file $TAR_SOURCE --directory=$BASEDIR $(git ls-tree -r master --name-only)
xz $TAR_SOURCE -9

cd $ANDROID_DIR
./gradlew build

AAR=$RELEASE_DIR/$PROJECT-$VERSION.aar
cp $ANDROID_DIR/tmpfile/build/outputs/aar/$PROJECT-release.aar $AAR

cd $RELEASE_DIR

FILES_TO_CHECKSUM="$TAR_SOURCE.xz $AAR"
CHECKSUM_FILE=$RELEASE_DIR/$PROJECT-$VERSION-checksums.txt
for f in $FILES_TO_CHECKSUM
do
  sha256sum --binary --tag $(basename $f) >> $CHECKSUM_FILE
  sha512sum --binary --tag $(basename $f) >> $CHECKSUM_FILE
done

echo "Checksums:"
cat $CHECKSUM_FILE

echo "Files to release:"
ls -lh $FILES_TO_CHECKSUM $CHECKSUM_FILE

