#!/bin/sh

# This project contains several places which refer to string "tmpfile-1.0.0.aar"
# This script parses project version from tmpfile/build.gradle and updates:
# README.md
# build.gradle of sampleapp,
# dobuild-sampleapp
# doclean

set -euo pipefail
shopt -s failglob

THIS_FILE=$(readlink -f "$0")
BASEDIR=$(dirname "$THIS_FILE")

# Extract project version from build.gradle
# Format:
# android { .... defaultConfig { ... versionName "1.0.0" ... } ... }
GRADLE_FILE=$BASEDIR/tmpfile/build.gradle
version_format='([0-9\.]+)'
expression="s/.*?versionName \"$version_format\".*?/\1/p"
VERSION=$(tr "\n" ' ' < $GRADLE_FILE | sed -En "--expression=$expression")

aar_file_search="tmpfile-$version_format.aar"
aar_file_replace="tmpfile-$VERSION.aar"
expression="s/$aar_file_search/$aar_file_replace/g"

README_FILE=$BASEDIR/README.md
sed -E "--expression=$expression" -i $README_FILE

SAMPLE_APP_GRADLE_FILE=$BASEDIR/sampleapp/app/build.gradle
sed -E "--expression=$expression" -i $SAMPLE_APP_GRADLE_FILE

DOBUILD_SAMPLEAPP_FILE=$BASEDIR/dobuild-sampleapp
sed -E "--expression=$expression" -i $DOBUILD_SAMPLEAPP_FILE

DOCLEAN_FILE=$BASEDIR/doclean
sed -E "--expression=$expression" -i $DOCLEAN_FILE

